# Generated by Django 2.0.3 on 2018-03-30 15:37

from django.db import migrations, models
import django_multiinfo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Posted')], default=django_multiinfo.models.SmsStatus(0))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('posted', models.DateTimeField(blank=True, null=True)),
                ('to', models.CharField(blank=True, max_length=15, null=True)),
                ('body', models.TextField()),
            ],
        ),
    ]
