# Generated by Django 2.0.4 on 2018-04-27 15:08

from django.db import migrations, models
import django.db.models.deletion
import django_multiinfo.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_multiinfo', '0002_auto_20180405_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_error', models.TextField(blank=True, null=True)),
                ('ts', models.DateTimeField(auto_now=True)),
                ('body_type', models.PositiveSmallIntegerField()),
                ('encoding', models.PositiveSmallIntegerField()),
                ('connector_id', models.BigIntegerField()),
                ('sms_id', models.BigIntegerField()),
                ('last_change_date', models.DateTimeField()),
                ('message_status', models.PositiveSmallIntegerField(choices=[('21', 'Wiadomość przesłana pomyślnie'), ('11', 'Błąd fatalny, wysyłanie nieudane'), ('3', 'Wiadomość przekazana do SMSC, oczekiwanie potwierdzenie doręczenia wiadomości'), ('7', 'Wiadomość wstrzymana z powodu przekroczenia limitu'), ('12', 'Wiadomość przedawniona'), ('13', 'Wiadomość usunięta'), ('0', 'Wiadomość przyjęta do przetwarzania'), ('1', 'Wiadomość w trakcie przetwarzania')])),
                ('priority', models.PositiveSmallIntegerField()),
                ('protocol', models.PositiveSmallIntegerField()),
                ('report_delivery', models.BooleanField()),
                ('request_status', models.IntegerField()),
                ('service_id', models.IntegerField()),
                ('response_to_id', models.BigIntegerField()),
                ('send_date', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('sender_name', models.CharField(max_length=150)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='eid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Posted'), (2, 'Busy'), (3, 'Error'), (4, 'Discarded')], default=django_multiinfo.models.SmsStatus(0)),
        ),
        migrations.AddField(
            model_name='smsmessageinfo',
            name='sms_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_multiinfo.SmsMessage'),
        ),
    ]
