# Generated by Django 2.0.4 on 2018-05-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_multiinfo', '0005_smsmessageinfo_dest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='ts',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
